### ISSUE TITLE
希望可以改进或添加以下内容，谢谢

### ISSUE THREAD

**Issue by lcross222** [ShangJixin/Typecho-Theme-JiWater#1]
1、头像问题：
main.css的3248行
#intro .logo {
		border-bottom: 0;
		display: inline-block;
		margin: 0 0 1em 0;
		overflow: hidden;
		position: relative;
		width: 4em;
	}
中display: inline-block表现不完美，我删除了，或许你可以用圆或者其他的，你这个旁边有白的部分。
2、添加背景图片
可以添加一个背景图片选项。
本人是小白，不会写代码，给个参考
<style> 
body {
	background: url(地址) no-repeat 100%;
	background-repeat: no-repeat;
	background-attachment: fixed;
	background-size: cover;
        background-position: left top;

}
</style>
3、如果有背景图片了的话，侧栏Sidebar可以加个半透明的背景吗？不遮挡背景，而且可以稍微凸显侧栏内容。
我是一个小白，不是很懂代码，只是一个idea。总体来说很完美了，加油！

**Comment by ShangJixin** [comment]
其实这个主题是从html5up那块扣下来的QwQ 我尽量在使用原模板提供的css 由于对中文字体显示有点不太友好所以就弃坑了...
